// tests.js — Ərəbcə söz mənası testləri (dini testlər silinib, yalnız məna sualları qalıb)
const questionsData = [
    {"type":"choice","category":"verb_meaning","question":"«كَتَبَ» sözünün mənası nədir?","options":["yazmaq","şəfaət etmək","zövq almaq","ehtiram etmək, ikram göstərmək"],"correct":0,"id":1},
    {"type":"choice","category":"az_to_arabic","question":"«oxumaq» sözünün ərəbcəsi hansıdır?","options":["تَخَيَّلَ","قَبَضَ","صَبَرَ","قَرَأَ"],"correct":3,"id":2},
    {"type":"choice","category":"verb_meaning","question":"«دَرَسَ» sözünün mənası nədir?","options":["adlandırmaq","unutdurmaq","kəsmək, qurban kəsmək","öyrənmək, dərs oxumaq"],"correct":3,"id":3},
    {"type":"choice","category":"az_to_arabic","question":"«baxmaq» sözünün ərəbcəsi hansıdır?","options":["اِمْتَلَكَ","نَظَرَ","قَرَّرَ","اِسْتَقْبَلَ"],"correct":1,"id":4},
    {"type":"choice","category":"verb_meaning","question":"«دَخَلَ» sözünün mənası nədir?","options":["niyyət etmək, yönəlmək","təklif etmək","uzanmaq","girmək"],"correct":3,"id":5},
    {"type":"choice","category":"az_to_arabic","question":"«oturmaq» sözünün ərəbcəsi hansıdır?","options":["جَلَسَ","صَنَّفَ","ذَمَّ","أَنْهَى"],"correct":0,"id":6},
    {"type":"choice","category":"verb_meaning","question":"«مَشَى» sözünün mənası nədir?","options":["etiraz etmək","paylamaq","əmin olmaq","yerimək"],"correct":3,"id":7},
    {"type":"choice","category":"az_to_arabic","question":"«minmək» sözünün ərəbcəsi hansıdır?","options":["رَجَا","رَكِبَ","اِسْتَدَلَّ","مَطَرَ"],"correct":1,"id":8},
    {"type":"choice","category":"verb_meaning","question":"«لَعِبَ» sözünün mənası nədir?","options":["yüksəlmək","bacarıq göstərmək","oynamaq","bağlamaq, müqavilə bağlamaq"],"correct":2,"id":9},
    {"type":"choice","category":"az_to_arabic","question":"«çəkmək (rəsm)» sözünün ərəbcəsi hansıdır?","options":["اِلْتَزَمَ بِالسُّنَّةِ","أَوْضَحَ","رَسَمَ","تَرَكَ"],"correct":2,"id":10},
    {"type":"choice","category":"verb_meaning","question":"«اِشْتَرَى» sözünün mənası nədir?","options":["müzakirə etmək, mübahisə aparmaq","narahat olmaq","almaq (satın almaq)","yardım istəmək"],"correct":2,"id":11},
    {"type":"choice","category":"az_to_arabic","question":"«satmaq» sözünün ərəbcəsi hansıdır?","options":["بَاعَ","اِسْتَنَدَ","أَحَبَّ","تَعَيَّنَ"],"correct":0,"id":12},
    {"type":"choice","category":"verb_meaning","question":"«بَكَى» sözünün mənası nədir?","options":["ağlamaq","qonağa ikram etmək","müşahidə etmək","elan etmək"],"correct":0,"id":13},
    {"type":"choice","category":"az_to_arabic","question":"«gülmək» sözünün ərəbcəsi hansıdır?","options":["شَكَّلَ","أَلْبَسَ","ثَبَتَ","ضَحِكَ"],"correct":3,"id":14},
    {"type":"choice","category":"verb_meaning","question":"«دَعَا» sözünün mənası nədir?","options":["dua etmək, çağırmaq","cəlb etmək","dəlil gətirmək","namazı qorumaq"],"correct":0,"id":15},
    {"type":"choice","category":"az_to_arabic","question":"«tövbə etmək» sözünün ərəbcəsi hansıdır?","options":["اِبْتَسَمَ","اِنْغَلَقَ","تَابَ","دَقَّقَ"],"correct":2,"id":16},
    {"type":"choice","category":"verb_meaning","question":"«تَعَلَّمَ» sözünün mənası nədir?","options":["yaxşı olmaq","ölmək","öyrənmək","möhkəmləndirmək, sabitləşdirmək"],"correct":2,"id":17},
    {"type":"choice","category":"az_to_arabic","question":"«öyrətmək» sözünün ərəbcəsi hansıdır?","options":["مَكُثَ","اِنْقَطَعَ عَنِ المَعْصِيَةِ","عَلَّمَ","تَصَالَحَ"],"correct":2,"id":18},
    {"type":"choice","category":"verb_meaning","question":"«صَامَ تَطَوُّعًا» sözünün mənası nədir?","options":["Allaha təvəkkül et","aşmaq, keçmək","könüllü oruc tutmaq","kömək etmək"],"correct":2,"id":19},
    {"type":"choice","category":"az_to_arabic","question":"«qorumaq, mühafizə etmək» sözünün ərəbcəsi hansıdır?","options":["رَضِيَ","اِسْتَمْتَعَ","رَكَعَ","حَافَظَ"],"correct":3,"id":20},
    {"type":"choice","category":"verb_meaning","question":"«بَشَّرَ» sözünün mənası nədir?","options":["pisləmək","müşahidə etmək","müsibətdə başsağlığı vermək","müjdələmək"],"correct":3,"id":21},
    {"type":"choice","category":"az_to_arabic","question":"«xəbərdarlıq etmək» sözünün ərəbcəsi hansıdır?","options":["حَذَّرَ","أَخَذَ","عَلَّمَ","اِتَّجَرَ"],"correct":0,"id":22},
    {"type":"choice","category":"verb_meaning","question":"«رَجَا» sözünün mənası nədir?","options":["köçürmək, nəql etmək","dayandırmaq","qəbul etmək","ümid etmək"],"correct":3,"id":23},
    {"type":"choice","category":"az_to_arabic","question":"«sevmək» sözünün ərəbcəsi hansıdır?","options":["زَارَ","أَغْضَبَ","تَدَاوَلَ","أَحَبَّ"],"correct":3,"id":24},
    {"type":"choice","category":"verb_meaning","question":"«اِلْتَزَمَ» sözünün mənası nədir?","options":["müstəqil olmaq","gecikdirmək","səhv etmək","bağlı qalmaq, riayət etmək"],"correct":3,"id":25},
    {"type":"choice","category":"az_to_arabic","question":"«düz yolda olmaq, istiqamət sahibi olmaq» sözünün ərəbcəsi hansıdır?","options":["اِرْتَفَعَ","اِسْتَقَامَ","أَثَابَ","قَلَّبَ"],"correct":1,"id":26},
    {"type":"choice","category":"verb_meaning","question":"«غَابَ» sözünün mənası nədir?","options":["ayırmaq, təyin etmək","qeyb olmaq, iştirak etməmək","təsnif etmək","mükafatlandırmaq"],"correct":1,"id":27},
    {"type":"choice","category":"az_to_arabic","question":"«hesab etmək, özünü sorğu-sual etmək» sözünün ərəbcəsi hansıdır?","options":["اِنْقَلَبَ","أَوْقَفَ","اِغْتَسَلَ","حَاسَبَ"],"correct":3,"id":28},
    {"type":"choice","category":"verb_meaning","question":"«تَقَدَّمَ» sözünün mənası nədir?","options":["sürmək","həyalı olmaq, örtünmək","irəli getmək, tərəqqi etmək","azalmaq"],"correct":2,"id":29},
    {"type":"choice","category":"az_to_arabic","question":"«həris olmaq, can atmaq» sözünün ərəbcəsi hansıdır?","options":["أَخْطَرَ","أَقْنَعَ","حَرَصَ","شَغَّلَ"],"correct":2,"id":30},
    {"type":"choice","category":"verb_meaning","question":"«وَقَّرَ» sözünün mənası nədir?","options":["batil olmaq, puç olmaq","ehtiram etmək, hörmət göstərmək","girmək","tərbiyə etmək"],"correct":1,"id":31},
    {"type":"choice","category":"az_to_arabic","question":"«ehtiram etmək, sayğı göstərmək» sözünün ərəbcəsi hansıdır?","options":["وَجَدَ","قَطَعَ","بَلَّغَ","اِحْتَرَمَ"],"correct":3,"id":32},
    {"type":"choice","category":"verb_meaning","question":"«اِفْتَرَقَ» sözünün mənası nədir?","options":["çoxalmaq","ayrılmaq, ayrı düşmək","rəftar etmək","çəkmək (rəsm)"],"correct":1,"id":33},
    {"type":"choice","category":"az_to_arabic","question":"«barışmaq, sülh etmək» sözünün ərəbcəsi hansıdır?","options":["هَيَّأَ","تَسَاءَلَ","قَصَّ","اِصْطَلَحَ"],"correct":3,"id":34},
    {"type":"choice","category":"verb_meaning","question":"«سَلَّمَ» sözünün mənası nədir?","options":["tutmaq","salam vermək, təslim etmək","zəmanət vermək","zülm etmək"],"correct":1,"id":35},
    {"type":"choice","category":"az_to_arabic","question":"«əl sıxmaq, görüşmək» sözünün ərəbcəsi hansıdır?","options":["أَلْهَمَ","صَافَحَ","رَغِبَ","كَشَفَ"],"correct":1,"id":36},
    {"type":"choice","category":"verb_meaning","question":"«اِنْقَطَعَ» sözünün mənası nədir?","options":["xütbəni dinləmək","fərqləndirmək","razı salmaq","kəsilmək, ayrılmaq, tərk etmək"],"correct":3,"id":37},
    {"type":"choice","category":"az_to_arabic","question":"«tərk etmək, buraxmaq» sözünün ərəbcəsi hansıdır?","options":["تَرَكَ","قَيَّسَ","اِعْتَرَضَ","حَكَى"],"correct":0,"id":38},
    {"type":"choice","category":"verb_meaning","question":"«تَدَاوَلَ» sözünün mənası nədir?","options":["soyutmaq","müzakirə etmək, danışmaq","ixtisaslaşmaq","qeyd etmək"],"correct":1,"id":39},
    {"type":"choice","category":"az_to_arabic","question":"«dəlil gətirmək, sübut etmək» sözünün ərəbcəsi hansıdır?","options":["اِسْتَمَرَّ","اِسْتَدَلَّ","صَوَّرَ","خَطِرَ"],"correct":1,"id":40},
    {"type":"choice","category":"verb_meaning","question":"«آمَنَ» sözünün mənası nədir?","options":["təkbir gətirmək, Allahı uca tutmaq","qalmaq","zidd getmək","iman gətirmək"],"correct":3,"id":41},
    {"type":"choice","category":"az_to_arabic","question":"«şirk qoşmaq» sözünün ərəbcəsi hansıdır?","options":["أَشْرَكَ","خَلَعَ","وَجَدَ","اِتَّهَمَ"],"correct":0,"id":42},
    {"type":"choice","category":"verb_meaning","question":"«ضَلَّ» sözünün mənası nədir?","options":["çətinləşdirmək","yaxşılaşmaq","həyəcanlanmaq","zəlalətə düşmək, yoldan çıxmaq"],"correct":3,"id":43},
    {"type":"choice","category":"az_to_arabic","question":"«bağışlamaq» sözünün ərəbcəsi hansıdır?","options":["اِرْتَدَى","تَأَخَّرَ","رَاحَ","غَفَرَ"],"correct":3,"id":44},
    {"type":"choice","category":"verb_meaning","question":"«عَمَّرَ» sözünün mənası nədir?","options":["həsrət qalmaq, arzulamaq","tikmək, abadlaşdırmaq, uzun ömür yaşamaq","itaət etmək, boyun əymək","adlandırmaq"],"correct":1,"id":45},
    {"type":"choice","category":"az_to_arabic","question":"«uçurmaq, sökmək» sözünün ərəbcəsi hansıdır?","options":["ذَكَرَ اللَّهَ","صَدَقَ","اِسْتَحَقَّ","هَدَمَ"],"correct":3,"id":46},
    {"type":"choice","category":"verb_meaning","question":"«اِتَّجَرَ» sözünün mənası nədir?","options":["çevirmək","itaətdə davamlı olmaq","işdən sonra istirahət etmək","ticarət etmək"],"correct":3,"id":47},
    {"type":"choice","category":"az_to_arabic","question":"«aldatmaq, fırıldaq etmək» sözünün ərəbcəsi hansıdır?","options":["صَاحَ","نَامَ","غَشَّ","طَبَخَ"],"correct":2,"id":48},
    {"type":"choice","category":"verb_meaning","question":"«اِسْتَغْلَى» sözünün mənası nədir?","options":["atmaq","fərqinə varmaq","bahalı saymaq, baha qiymətləndirmək","dalmaq"],"correct":2,"id":49},
    {"type":"choice","category":"az_to_arabic","question":"«ucuz saymaq, endirim etmək» sözünün ərəbcəsi hansıdır?","options":["زَارَ","اِسْتَخْفَضَ","اِحْتَاجَ","حَاضَرَ"],"correct":1,"id":50},
    {"type":"choice","category":"verb_meaning","question":"«تَزَكَّى» sözünün mənası nədir?","options":["təmizlənmək, zəkat vermək","kirayə vermək","faydalanmaq","cəhd etmək"],"correct":0,"id":51},
    {"type":"choice","category":"az_to_arabic","question":"«ehtiyacsız olmaq, qənaət etmək» sözünün ərəbcəsi hansıdır?","options":["عَاقَبَ","سَمِعَ","قَسَا","اِسْتَغْنَى"],"correct":3,"id":52},
    {"type":"choice","category":"verb_meaning","question":"«اِخْتَالَ» sözünün mənası nədir?","options":["rahatlamaq, sakit olmaq","yola salmaq","lovğalanmaq, özünü bəyənmək","elan etmək"],"correct":2,"id":53},
    {"type":"choice","category":"az_to_arabic","question":"«fəxr etmək, qürur hissi» sözünün ərəbcəsi hansıdır?","options":["زَوَّجَ","اِنْخَفَضَ","اِفْتَخَرَ","أَفْسَدَ"],"correct":2,"id":54},
    {"type":"choice","category":"verb_meaning","question":"«قَصَّ» sözünün mənası nədir?","options":["söz gəzdirmək, namazlıq etmək","hekayə danışmaq","qoşmaq","doğramaq"],"correct":1,"id":55},
    {"type":"choice","category":"az_to_arabic","question":"«qısa danışmaq, icmal etmək» sözünün ərəbcəsi hansıdır?","options":["أَوْجَزَ","أَقْنَعَ","أَفْهَمَ","هَدَمَ"],"correct":0,"id":56},
    {"type":"choice","category":"verb_meaning","question":"«اِجْتَنَبَ» sözünün mənası nədir?","options":["nəsihət etmək","uzaq durmaq, çəkinmək","ehtiyat etmək","müayinə etmək, yoxlamaq"],"correct":1,"id":57},
    {"type":"choice","category":"az_to_arabic","question":"«riayət etmək, bağlı qalmaq» sözünün ərəbcəsi hansıdır?","options":["اِسْتَقَامَ","اِلْتَزَمَ","شَارَكَ","أَكَلَ"],"correct":1,"id":58},
    {"type":"choice","category":"verb_meaning","question":"«نَقَصَ» sözünün mənası nədir?","options":["uca tutmaq","güclənmək","azalmaq, əskilmək","çətinləşdirmək"],"correct":2,"id":59},
    {"type":"choice","category":"az_to_arabic","question":"«tamamlanmaq, tam olmaq» sözünün ərəbcəsi hansıdır?","options":["كَنسَ","أَفْرَحَ","طَوَى","كَمَلَ"],"correct":3,"id":60},
    {"type":"choice","category":"verb_meaning","question":"«حَقَّ» sözünün mənası nədir?","options":["təsəvvür etmək","haqq olmaq, doğru olmaq","tələsmək","əsir almaq"],"correct":1,"id":61},
    {"type":"choice","category":"az_to_arabic","question":"«haqq etmək, layiq olmaq» sözünün ərəbcəsi hansıdır?","options":["اِسْتَحَقَّ","جَاءَ","أَجَّلَ","صَلَّى"],"correct":0,"id":62},
    {"type":"choice","category":"verb_meaning","question":"«اِشْتَاقَ» sözünün mənası nədir?","options":["həsrət qalmaq, arzulamaq","öhdəsinə götürmək","pisləmək","Quranda təfəkkür etmək"],"correct":0,"id":63},
    {"type":"choice","category":"az_to_arabic","question":"«rahatlamaq, sakit olmaq» sözünün ərəbcəsi hansıdır?","options":["اِطْمَأَنَّ","بَدَا","اِشْتَبَهَ","شَكَّلَ"],"correct":0,"id":64},
    {"type":"choice","category":"verb_meaning","question":"«اِقْتَدَى» sözünün mənası nədir?","options":["uymaq, tabe olmaq (imama)","dondurmaq","istifadə etmək","etiraz etmək"],"correct":0,"id":65},
    {"type":"choice","category":"az_to_arabic","question":"«xütbəni dinləmək» sözünün ərəbcəsi hansıdır?","options":["اِسْتَمَعَ إِلَى الخُطْبَةِ","أَصْلَحَ","أَنْهَى","فَتَّحَ"],"correct":0,"id":66},
    {"type":"choice","category":"verb_meaning","question":"«كَذَّبَ» sözünün mənası nədir?","options":["dönmək, yönəlmək","isinmək","bərabərləşdirmək","yalançı saymaq, inkar etmək"],"correct":3,"id":67},
    {"type":"choice","category":"az_to_arabic","question":"«istehza etmək, lağ etmək» sözünün ərəbcəsi hansıdır?","options":["اِنْقَلَبَ","اِسْتَهْزَأَ","سَرَّ","هَدَأَ"],"correct":1,"id":68},
    {"type":"choice","category":"verb_meaning","question":"«غَضِبَ» sözünün mənası nədir?","options":["axtarmaq","gülümsəmək","qarşılaşmaq","qəzəblənmək"],"correct":3,"id":69},
    {"type":"choice","category":"az_to_arabic","question":"«intiqam almaq» sözünün ərəbcəsi hansıdır?","options":["ذَاقَ","اِنْزَعَجَ","اِنْتَقَمَ","اِعْتَنَى"],"correct":2,"id":70},
    {"type":"choice","category":"verb_meaning","question":"«حَافَظَ عَلَى الصَّلَاةِ» sözünün mənası nədir?","options":["müstəqil olmaq","yedirtmək, yemək vermək","namazı qorumaq","yoldaş olmaq, dostluq etmək"],"correct":2,"id":71},
    {"type":"choice","category":"az_to_arabic","question":"«yerinə yetirmək, ödəmək» sözünün ərəbcəsi hansıdır?","options":["قَبِلَ","أَدَّى","اِتَّسَعَ","تَكَبَّرَ"],"correct":1,"id":72},
    {"type":"choice","category":"verb_meaning","question":"«اِسْتَرَاحَ» sözünün mənası nədir?","options":["uğur qazanmaq","istirahət etmək","zöhd etmək","istifadə etmək"],"correct":1,"id":73},
    {"type":"choice","category":"az_to_arabic","question":"«düşünmək, tələsməmək» sözünün ərəbcəsi hansıdır?","options":["زَادَ","تَرَوَّى","اِسْتَنَدَ","اِتَّجَهَ"],"correct":1,"id":74},
    {"type":"choice","category":"verb_meaning","question":"«اِجْتَهَدَ فِي العِبَادَةِ» sözünün mənası nədir?","options":["ibadətdə səy göstərmək","yayılmaq","işləmək","doldurmaq"],"correct":0,"id":75},
    {"type":"choice","category":"az_to_arabic","question":"«itaətdə davamlı olmaq» sözünün ərəbcəsi hansıdır?","options":["اِنْهَزَمَ","اِحْتَجَزَ","اِسْتَمَرَّ فِي الطَّاعَةِ","صَعِدَ"],"correct":2,"id":76},
    {"type":"choice","category":"verb_meaning","question":"«ذَكَرَ اللَّهَ» sözünün mənası nədir?","options":["girməzdən əvvəl icazə istəmək","olmaq, səhər olmaq","əyilmək","Allahı zikr etmək"],"correct":3,"id":77},
    {"type":"choice","category":"az_to_arabic","question":"«təsbih etmək, Allahı təqdis etmək» sözünün ərəbcəsi hansıdır?","options":["سَبَّحَ","شَرَحَ","أَخْلَفَ","أَطْفَأَ"],"correct":0,"id":78},
    {"type":"choice","category":"verb_meaning","question":"«اِعْتَصَمْ بِاللَّهِ» sözünün mənası nədir?","options":["ziyarət etmək","tapdalamaq","Allahdan yapış, Ona sarıl","bəxş etmək"],"correct":2,"id":79},
    {"type":"choice","category":"az_to_arabic","question":"«haqqa sarılmaq» sözünün ərəbcəsi hansıdır?","options":["أَسْرَعَ","أَبْدَى","اِسْتَمْسَكَ بِالحَقِّ","أَعْجَبَ"],"correct":2,"id":80},
    {"type":"choice","category":"verb_meaning","question":"«رَضِيَ بِقَضَاءِ اللَّهِ» sözünün mənası nədir?","options":["Allahın qəzasına razı olmaq","qarışmaq","bərabərləşdirmək","izləmək"],"correct":0,"id":81},
    {"type":"choice","category":"az_to_arabic","question":"«bəlaya səbir etmək» sözünün ərəbcəsi hansıdır?","options":["ضَلَّ","شَرِبَ","اِنْتَظَمَ","صَبَرَ عَلَى البَلَاءِ"],"correct":3,"id":82},
    {"type":"choice","category":"verb_meaning","question":"«تَأَمَّلَ فِي القُرْآنِ» sözünün mənası nədir?","options":["imtina etmək","Quranda təfəkkür etmək","çevirib baxmaq","ittiham etmək"],"correct":1,"id":83},
    {"type":"choice","category":"az_to_arabic","question":"«elmdən faydalanmaq» sözünün ərəbcəsi hansıdır?","options":["فَكَّرَ","اِسْتَفَادَ مِنَ العِلْمِ","عَانَقَ","رَفَعَ"],"correct":1,"id":84},
    {"type":"choice","category":"verb_meaning","question":"«اِسْتَمْسَكَ بِالعَقِيدَةِ» sözünün mənası nədir?","options":["dalmaq","hiss etmək","əqidəyə sarılmaq","bacarmaq"],"correct":2,"id":85},
    {"type":"choice","category":"az_to_arabic","question":"«sünnəyə tabe olmaq» sözünün ərəbcəsi hansıdır?","options":["اِنْتَقَلَ","تَصَالَحَ","قَيَّسَ","اِتَّبَعَ السُّنَّةَ"],"correct":3,"id":86},
    {"type":"choice","category":"verb_meaning","question":"«أَكْرَمَ الضَّيْفَ» sözünün mənası nədir?","options":["doğru olmaq, səhih olmaq","təsvir etmək","qonağa ikram etmək","sabitləşdirmək"],"correct":2,"id":87},
    {"type":"choice","category":"az_to_arabic","question":"«yerləşmək, sabit olmaq» sözünün ərəbcəsi hansıdır?","options":["اِسْتَقْبَحَ","بَدَا","شَبَّهَ","اِسْتَقَرَّ فِي المَكَانِ"],"correct":3,"id":88},
    {"type":"choice","category":"verb_meaning","question":"«وَقَفَ» sözünün mənası nədir?","options":["müşayiət etmək","namaza hazırlaşmaq","izləmək","dayanmaq"],"correct":3,"id":89},
    {"type":"choice","category":"az_to_arabic","question":"«qaçmaq» sözünün ərəbcəsi hansıdır?","options":["اِسْتَفْسَرَ","أَعَدَّ","رَكَضَ","تَأَثَّرَ"],"correct":2,"id":90},
    {"type":"choice","category":"verb_meaning","question":"«رَغِبَ» sözünün mənası nədir?","options":["ehtiram etmək, hörmət göstərmək","istəmək","namaz qılmaq","etiraz etmək"],"correct":1,"id":91},
    {"type":"choice","category":"az_to_arabic","question":"«istəmək, tələb etmək» sözünün ərəbcəsi hansıdır?","options":["خَفَّ","طَلَبَ","اِقْتَصَدَ","تَعَلَّمَ"],"correct":1,"id":92},
    {"type":"choice","category":"verb_meaning","question":"«فَشِلَ» sözünün mənası nədir?","options":["mükafatlandırmaq","nəql etmək","oyanmaq","uğursuz olmaq"],"correct":3,"id":93},
    {"type":"choice","category":"az_to_arabic","question":"«qazanmaq» sözünün ərəbcəsi hansıdır?","options":["ضَيَّقَ","رَبِحَ","تَصَرَّفَ","اِسْتَمَرَّ فِي الطَّاعَةِ"],"correct":1,"id":94},
    {"type":"choice","category":"verb_meaning","question":"«غَادَرَ» sözünün mənası nədir?","options":["boşalmaq","tərk etmək","uzaq durmaq, çəkinmək","sakitləşdirmək"],"correct":1,"id":95},
    {"type":"choice","category":"az_to_arabic","question":"«qalmaq» sözünün ərəbcəsi hansıdır?","options":["بَقِيَ","تَرَاجَعَ","شَارَكَ","حَزِنَ"],"correct":0,"id":96},
    {"type":"choice","category":"verb_meaning","question":"«أَبْطَأَ» sözünün mənası nədir?","options":["yavaşlatmaq","fətva istəmək","yola salmaq","yerinə yetirmək, ödəmək"],"correct":0,"id":97},
    {"type":"choice","category":"az_to_arabic","question":"«dayanmaq» sözünün ərəbcəsi hansıdır?","options":["ذَبَحَ","تَعَامَلَ","تَوَحَّدَ","تَوَقَّفَ"],"correct":3,"id":98},
    {"type":"choice","category":"verb_meaning","question":"«كَرَّرَ» sözünün mənası nədir?","options":["çıxmaq","təkrarlamaq","sədəqə vermək","təvazökar olmaq, qəlbi yumşalmaq"],"correct":1,"id":99},
    {"type":"choice","category":"az_to_arabic","question":"«dəyişmək» sözünün ərəbcəsi hansıdır?","options":["أَخْفَى","غَيَّرَ","قَبِلَ","وَقَّرَ"],"correct":1,"id":100},
    {"type":"choice","category":"verb_meaning","question":"«نَفَعَ» sözünün mənası nədir?","options":["fayda vermək","ittiham etmək","yandırmaq","əmin olmaq"],"correct":0,"id":101},
    {"type":"choice","category":"az_to_arabic","question":"«zərər vermək» sözünün ərəbcəsi hansıdır?","options":["قَدَرَ","نَجَا","ضَرَّ","اِتَّعَظَ"],"correct":2,"id":102},
    {"type":"choice","category":"verb_meaning","question":"«رَكَّزَ» sözünün mənası nədir?","options":["xəbər vermək","cəmləmək","elmdən faydalanmaq","kirayə götürmək, işə almaq"],"correct":1,"id":103},
    {"type":"choice","category":"az_to_arabic","question":"«düşünmək» sözünün ərəbcəsi hansıdır?","options":["جَاءَ","أَعَادَ","أَحْزَنَ","فَكَّرَ"],"correct":3,"id":104},
    {"type":"choice","category":"verb_meaning","question":"«تَأَكَّدَ» sözünün mənası nədir?","options":["evləndirmək","əmin olmaq","oyanmaq","minmək"],"correct":1,"id":105},
    {"type":"choice","category":"az_to_arabic","question":"«yoxlamaq, gerçəkləşmək» sözünün ərəbcəsi hansıdır?","options":["أَجَّرَ","اِسْتَغْلَقَ","تَزَكَّى","تَحَقَّقَ"],"correct":3,"id":106},
    {"type":"choice","category":"verb_meaning","question":"«تَكَلَّمَ» sözünün mənası nədir?","options":["doğramaq","qeybət etmək","danışmaq","sevinmək"],"correct":2,"id":107},
    {"type":"choice","category":"az_to_arabic","question":"«susmaq» sözünün ərəbcəsi hansıdır?","options":["أَمَاتَ","صَمَتَ","كَفَرَ","دَعَا اللَّهَ"],"correct":1,"id":108},
    {"type":"choice","category":"verb_meaning","question":"«أَرْسَلَ» sözünün mənası nədir?","options":["göndərmək","zöhd etmək","itməy","təmizləmək"],"correct":0,"id":109},
    {"type":"choice","category":"az_to_arabic","question":"«qəbul etmək» sözünün ərəbcəsi hansıdır?","options":["أَجَابَ","شَجَّعَ","اِسْتَلَمَ","تَحَدَّثَ"],"correct":2,"id":110},
    {"type":"choice","category":"verb_meaning","question":"«أَخَّرَ» sözünün mənası nədir?","options":["tabe olmaq, izləmək","bağlamaq","ehtiyat etmək","gecikdirmək"],"correct":3,"id":111},
    {"type":"choice","category":"az_to_arabic","question":"«qoymaq» sözünün ərəbcəsi hansıdır?","options":["كَثُرَ","اِتَّقَى","حَسَبَ","وَضَعَ"],"correct":3,"id":112},
    {"type":"choice","category":"verb_meaning","question":"«عَقَدَ» sözünün mənası nədir?","options":["danışmaq","inkar etmək, rədd etmək","bağlamaq, müqavilə bağlamaq","çıxarmaq"],"correct":2,"id":113},
    {"type":"choice","category":"az_to_arabic","question":"«açmaq, çözmək» sözünün ərəbcəsi hansıdır?","options":["قَتَلَ","تَجَنَّبَ","سَمَّى","فَكَّ"],"correct":3,"id":114},
    {"type":"choice","category":"verb_meaning","question":"«نَفَّذَ» sözünün mənası nədir?","options":["görüşmək, qarşılaşmaq","etiraf etmək","icra etmək","paylamaq"],"correct":2,"id":115},
    {"type":"choice","category":"az_to_arabic","question":"«tətbiq etmək» sözünün ərəbcəsi hansıdır?","options":["تَخَصَّصَ","طَبَّقَ","اِسْتَضَافَ","تَنَازَلَ"],"correct":1,"id":116},
    {"type":"choice","category":"verb_meaning","question":"«نَظَفَ» sözünün mənası nədir?","options":["Allahın nemətlərinə şükr etmək","təmizləmək","təhqir etmək, söymək","qaçınmaq"],"correct":1,"id":117},
    {"type":"choice","category":"az_to_arabic","question":"«təmizləmək» sözünün ərəbcəsi hansıdır?","options":["تَحَمَّلَ","دَخَلَ","نَظَّفَ","مَزَجَ"],"correct":2,"id":118},
    {"type":"choice","category":"verb_meaning","question":"«ذَاقَ» sözünün mənası nədir?","options":["tələsməmək","kökündən çıxarmaq","dadmaq","mühazirə vermək, dərs demək"],"correct":2,"id":119},
    {"type":"choice","category":"az_to_arabic","question":"«çeynəmək» sözünün ərəbcəsi hansıdır?","options":["غَادَرَ","حَافَظَ","مَضَغَ","اِسْتَقَلَّ"],"correct":2,"id":120},
    {"type":"choice","category":"verb_meaning","question":"«مَلَأَ» sözünün mənası nədir?","options":["sürüşmək","əzbərlətmək","izah etmək","doldurmaq"],"correct":3,"id":121},
    {"type":"choice","category":"az_to_arabic","question":"«boşaltmaq» sözünün ərəbcəsi hansıdır?","options":["رَكَلَ","اِعْتَقَدَ","فَرَّغَ","فَقَهَ"],"correct":2,"id":122},
    {"type":"choice","category":"verb_meaning","question":"«كَانَ» sözünün mənası nədir?","options":["ittiham etmək","mühafizə etmək","olmaq","kifayətlənmək"],"correct":2,"id":123},
    {"type":"choice","category":"az_to_arabic","question":"«çevrilmək, olmaq» sözünün ərəbcəsi hansıdır?","options":["اِحْتَقَرَ","طَبَخَ","تَثَبَّتَ","صَارَ"],"correct":3,"id":124},
    {"type":"choice","category":"verb_meaning","question":"«فَقَدَ» sözünün mənası nədir?","options":["dərs demək","itirmək","yüngülləşmək","gözləmək"],"correct":1,"id":125},
    {"type":"choice","category":"az_to_arabic","question":"«itməy» sözünün ərəbcəsi hansıdır?","options":["صَفَعَ","ضَاعَ","غَبَطَ","اِلْتَزَمَ بِالسُّنَّةِ"],"correct":1,"id":126},
    {"type":"choice","category":"verb_meaning","question":"«قَبِلَ» sözünün mənası nədir?","options":["dönmək","yardım istəmək","razı salmaq","qəbul etmək"],"correct":3,"id":127},
    {"type":"choice","category":"az_to_arabic","question":"«razılaşmaq» sözünün ərəbcəsi hansıdır?","options":["أَقْفَلَ","قَارَنَ","مَلَأَ","وَافَقَ"],"correct":3,"id":128},
    {"type":"choice","category":"verb_meaning","question":"«لَامَ» sözünün mənası nədir?","options":["günahdan çəkinmək","qınamaq","həll etmək","uca tutmaq"],"correct":1,"id":129},
    {"type":"choice","category":"az_to_arabic","question":"«etiraf etmək» sözünün ərəbcəsi hansıdır?","options":["تَصَالَحَ","أَلْحَقَ","اِعْتَرَفَ","اِجْتَنَبَ الشُّبُهَاتِ"],"correct":2,"id":130},
    {"type":"choice","category":"verb_meaning","question":"«دَخَّرَ» sözünün mənası nədir?","options":["yığmaq, qənaət etmək","həsrət qalmaq, arzulamaq","yaratmaq","ağlamaq"],"correct":0,"id":131},
    {"type":"choice","category":"az_to_arabic","question":"«yığmaq» sözünün ərəbcəsi hansıdır?","options":["اِدَّخَرَ","سَافَرَ","أَفْطَرَ","أَصْبَحَ"],"correct":0,"id":132},
    {"type":"choice","category":"verb_meaning","question":"«قَادَ» sözünün mənası nədir?","options":["geyinmək","qarşılıqlı əlaqədə olmaq","tərtib etmək, yazmaq","idarə etmək, sürmək"],"correct":3,"id":133},
    {"type":"choice","category":"az_to_arabic","question":"«sürmək» sözünün ərəbcəsi hansıdır?","options":["ظَنَّ","مَضَغَ","مَهَّدَ","سَاقَ"],"correct":3,"id":134},
    {"type":"choice","category":"verb_meaning","question":"«سَحَبَ» sözünün mənası nədir?","options":["yağmaq","açılmaq, genişlənmək (qəlb)","çəkmək","əmin olmaq"],"correct":2,"id":135},
    {"type":"choice","category":"az_to_arabic","question":"«atmaq» sözünün ərəbcəsi hansıdır?","options":["رَمَى","كَفَى","عَاهَدَ","اِسْتَخْلَصَ"],"correct":0,"id":136},
    {"type":"choice","category":"verb_meaning","question":"«اِمْتَلَكَ» sözünün mənası nədir?","options":["haqq üzərində sabit qalmaq","bağlamaq, qapatmaq","göndərmək","sahib olmaq"],"correct":3,"id":137},
    {"type":"choice","category":"az_to_arabic","question":"«layiq olmaq» sözünün ərəbcəsi hansıdır?","options":["تَحَذَّرَ","اِسْتَحَقَّ","أَرْسَلَ","أَجَلَّ"],"correct":1,"id":138},
    {"type":"choice","category":"verb_meaning","question":"«نَصَرَ» sözünün mənası nədir?","options":["kömək etmək, qalib etdirmək","uçurmaq, sökmək","hazırlamaq","üzə çıxmaq"],"correct":0,"id":139},
    {"type":"choice","category":"az_to_arabic","question":"«hücum etmək» sözünün ərəbcəsi hansıdır?","options":["هَاجَمَ","أَثَّرَ","أَجَابَ","حَنَى"],"correct":0,"id":140},
    {"type":"choice","category":"verb_meaning","question":"«اِحْتَلَّ» sözünün mənası nədir?","options":["yavaşlatmaq","faydalanmaq","doğru olmaq, səhih olmaq","işğal etmək"],"correct":3,"id":141},
    {"type":"choice","category":"az_to_arabic","question":"«qaçmaq» sözünün ərəbcəsi hansıdır?","options":["تَشَاجَرَ","هَرَبَ","أَدَانَ","اِسْتَثْنَى"],"correct":1,"id":142},
    {"type":"choice","category":"verb_meaning","question":"«وَجَّهَ» sözünün mənası nədir?","options":["dəqiqləşdirmək","yazmaq","tökmək","yönəltmək"],"correct":3,"id":143},
    {"type":"choice","category":"az_to_arabic","question":"«görüşmək, qarşılaşmaq» sözünün ərəbcəsi hansıdır?","options":["جَمَدَ","اِعْتَكَفَ","أَلْهَمَ","قَابَلَ"],"correct":3,"id":144},
    {"type":"choice","category":"verb_meaning","question":"«اِشْتَكَى» sözünün mənası nədir?","options":["şikayət etmək","təpik vurmaq","təcavüz etmək, həddi aşmaq","sübut etmək"],"correct":0,"id":145},
    {"type":"choice","category":"az_to_arabic","question":"«əziyyət çəkmək» sözünün ərəbcəsi hansıdır?","options":["عَانَى","اِسْتَفَادَ","اِنْقَلَبَ","طَارَدَ"],"correct":0,"id":146},
    {"type":"choice","category":"verb_meaning","question":"«اِسْتَفْهَمَ» sözünün mənası nədir?","options":["yandırmaq","soruşub aydınlaşdırmaq","şillə vurmaq","tikmək, qurmaq"],"correct":1,"id":147},
    {"type":"choice","category":"az_to_arabic","question":"«məlumat almaq» sözünün ərəbcəsi hansıdır?","options":["اِسْتَعْلَمَ","ظَلَّ","زَلَقَ","اِتَّسَعَ"],"correct":0,"id":148},
    {"type":"choice","category":"verb_meaning","question":"«قَارَنَ» sözünün mənası nədir?","options":["soruşub aydınlaşdırmaq","şükr etmək","müqayisə etmək","lə ilahə illəllah demək"],"correct":2,"id":149},
    {"type":"choice","category":"az_to_arabic","question":"«bənzətmək» sözünün ərəbcəsi hansıdır?","options":["شَبَّهَ","شَكَرَ اللَّهَ عَلَى نِعَمِهِ","بَدَعَ","رَوَى"],"correct":0,"id":150},
    {"type":"choice","category":"verb_meaning","question":"«قَاسَمَ» sözünün mənası nədir?","options":["oynamaq","bölüşmək","qəzəbləndirmək","təşviq etmək, ruhlandırmaq"],"correct":1,"id":151},
    {"type":"choice","category":"az_to_arabic","question":"«hesablamaq» sözünün ərəbcəsi hansıdır?","options":["بَرْمَجَ","حَسَبَ","تَزَوَّجَ","حَفِظَ"],"correct":1,"id":152},
    {"type":"choice","category":"verb_meaning","question":"«اِسْتَوْعَبَ» sözünün mənası nədir?","options":["dönmək","zülm etmək","qonağı qarşılamaq","tam qavramaq"],"correct":3,"id":153},
    {"type":"choice","category":"az_to_arabic","question":"«nəticə çıxarmaq» sözünün ərəbcəsi hansıdır?","options":["حَلَقَ","تَجَاوَزَ","وَصَلَ","اِسْتَنْتَجَ"],"correct":3,"id":154},
    {"type":"choice","category":"verb_meaning","question":"«طَوَّرَ» sözünün mənası nədir?","options":["geri qaytarmaq","tutmaq, almaq","təsvir etmək","inkişaf etdirmək"],"correct":3,"id":155},
    {"type":"choice","category":"az_to_arabic","question":"«inkişaf etmək» sözünün ərəbcəsi hansıdır?","options":["أُعْجِبَ","تَطَوَّرَ","وَظَّفَ","أَفْسَدَ"],"correct":1,"id":156},
    {"type":"choice","category":"verb_meaning","question":"«أَنْجَبَ» sözünün mənası nədir?","options":["hazırlamaq","nəticə çıxarmaq","övlad sahibi olmaq","tətbiq etmək"],"correct":2,"id":157},
    {"type":"choice","category":"az_to_arabic","question":"«evlənmək» sözünün ərəbcəsi hansıdır?","options":["تَزَوَّجَ","اِسْتَظْهَرَ","تَبَيَّنَ","زَكَّى"],"correct":0,"id":158},
    {"type":"choice","category":"verb_meaning","question":"«فَرَّجَ» sözünün mənası nədir?","options":["qalib gəlmək, zəfər çalmaq","əzib məhv etmək","rahatlatmaq","borc almaq"],"correct":2,"id":159},
    {"type":"choice","category":"az_to_arabic","question":"«kədərləndirmək» sözünün ərəbcəsi hansıdır?","options":["تَأَخَّرَ","أَحْزَنَ","مَسَحَ","صَمَّمَ"],"correct":1,"id":160},
    {"type":"choice","category":"verb_meaning","question":"«أَلْبَسَ» sözünün mənası nədir?","options":["geyindirmək","rəhm etmək, mərhəmət göstərmək","uçurmaq, sökmək","itirmək"],"correct":0,"id":161},
    {"type":"choice","category":"az_to_arabic","question":"«geyinmək» sözünün ərəbcəsi hansıdır?","options":["تَحَرَّى","أَخْفَى","تَرَاجَعَ","اِرْتَدَى"],"correct":3,"id":162},
    {"type":"choice","category":"verb_meaning","question":"«نَزَعَ» sözünün mənası nədir?","options":["çıxarmaq","sabitləşdirmək","etiraz etmək","bilmək"],"correct":0,"id":163},
    {"type":"choice","category":"az_to_arabic","question":"«kökündən çıxarmaq» sözünün ərəbcəsi hansıdır?","options":["كَذَّبَ","اِقْتَلَعَ","تَحَمَّلَ","اِسْتَنَدَ"],"correct":1,"id":164},
    {"type":"choice","category":"verb_meaning","question":"«أَبْعَدَ» sözünün mənası nədir?","options":["yüksəlmək","sezmək, görmək","qısa danışmaq, icmal etmək","uzaqlaşdırmaq"],"correct":3,"id":165},
    {"type":"choice","category":"az_to_arabic","question":"«yaxınlaşdırmaq» sözünün ərəbcəsi hansıdır?","options":["عَزَّى فِي المُصِيبَةِ","قَرَّبَ","أَوْفَى","ظَلَّ"],"correct":1,"id":166},
    {"type":"choice","category":"verb_meaning","question":"«رَاحَ» sözünün mənası nədir?","options":["getmək","yoxlamaq, gerçəkləşmək","ixtira etmək","fətva istəmək"],"correct":0,"id":167},
    {"type":"choice","category":"az_to_arabic","question":"«geri almaq, bərpa etmək» sözünün ərəbcəsi hansıdır?","options":["أَخْبَرَ","خَرِجَ","اِسْتَعَادَ","حَفَّظَ"],"correct":2,"id":168},
    {"type":"choice","category":"verb_meaning","question":"«فَقَهَ» sözünün mənası nədir?","options":["çıxmaq","anlamaq","içmək","tənqid etmək"],"correct":1,"id":169},
    {"type":"choice","category":"az_to_arabic","question":"«bilmək» sözünün ərəbcəsi hansıdır?","options":["قَدَرَ","أَمِنَ","أَمْسَى","دَرَى"],"correct":3,"id":170},
    {"type":"choice","category":"verb_meaning","question":"«أَنْشَأَ» sözünün mənası nədir?","options":["yaymaq","yaratmaq, qurmaq","dayanmaq","qınamaq"],"correct":1,"id":171},
    {"type":"choice","category":"az_to_arabic","question":"«əsasını qoymaq» sözünün ərəbcəsi hansıdır?","options":["أَسَّسَ","بَدَّلَ","سَبَحَ","حَمَلَ"],"correct":0,"id":172},
    {"type":"choice","category":"verb_meaning","question":"«أَوْقَدَ» sözünün mənası nədir?","options":["sünnəyə tabe olmaq","işarə etmək, göstərmək","kin saxlamaq, qərəz bəsləmək","yandırmaq"],"correct":3,"id":173},
    {"type":"choice","category":"az_to_arabic","question":"«alışdırmaq» sözünün ərəbcəsi hansıdır?","options":["حَقَدَ","أَشْعَلَ","تَصَوَّرَ","اِلْتَزَمَ بِالآدَابِ"],"correct":1,"id":174},
    {"type":"choice","category":"verb_meaning","question":"«بَرَّدَ» sözünün mənası nədir?","options":["köçürmək, nəql etmək","qərar vermək","yardım istəmək","soyutmaq"],"correct":3,"id":175},
    {"type":"choice","category":"az_to_arabic","question":"«qızdırmaq» sözünün ərəbcəsi hansıdır?","options":["تَرَوَّى","بَرْمَجَ","سَخَّنَ","اِشْتَبَهَ"],"correct":2,"id":176},
    {"type":"choice","category":"verb_meaning","question":"«بَلَّلَ» sözünün mənası nədir?","options":["islatmaq","üzmək","açmaq","detallaşdırmaq"],"correct":0,"id":177},
    {"type":"choice","category":"az_to_arabic","question":"«yağış yağmaq» sözünün ərəbcəsi hansıdır?","options":["عَادَ المَرِيضَ","فَقَدَ","أَنْسَى","مَطَرَ"],"correct":3,"id":178},
    {"type":"choice","category":"verb_meaning","question":"«حَوَّلَ» sözünün mənası nədir?","options":["layiq olmaq","hekayə danışmaq","sədəqə vermək","çevirmək"],"correct":3,"id":179},
    {"type":"choice","category":"az_to_arabic","question":"«çevrilmək» sözünün ərəbcəsi hansıdır?","options":["قَرَّرَ","نَصَحَ","تَحَوَّلَ","اِسْتَعْجَلَ"],"correct":2,"id":180},
    {"type":"choice","category":"verb_meaning","question":"«اِسْتَجْوَبَ» sözünün mənası nədir?","options":["sancmaq","hazırlamaq","sorğu-sual etmək","qızdırmaq"],"correct":2,"id":181},
    {"type":"choice","category":"az_to_arabic","question":"«həyata keçirmək, araşdırmaq» sözünün ərəbcəsi hansıdır?","options":["حَقَّقَ","زَهِدَ","اِتَّجَهَ","قَصُرَ"],"correct":0,"id":182},
    {"type":"choice","category":"verb_meaning","question":"«حَذَّرَ» sözünün mənası nədir?","options":["ölmək","dayanmaq","xəbərdar etmək","etiraz etmək"],"correct":2,"id":183},
    {"type":"choice","category":"az_to_arabic","question":"«ehtiyat etmək» sözünün ərəbcəsi hansıdır?","options":["حَذِرَ","حَفَرَ","خَرِجَ","قَصَّرَ"],"correct":0,"id":184},
    {"type":"choice","category":"verb_meaning","question":"«اِسْتَسْهَلَ» sözünün mənası nədir?","options":["narahat olmaq, təlaşa düşmək","işdən sonra istirahət etmək","kifayət etmək","asan saymaq"],"correct":3,"id":185},
    {"type":"choice","category":"az_to_arabic","question":"«çətin saymaq» sözünün ərəbcəsi hansıdır?","options":["عَلَّمَ","تَصَالَحَ","اِعْتَرَفَ","اِسْتَصْعَبَ"],"correct":3,"id":186},
    {"type":"choice","category":"verb_meaning","question":"«اِهْتَاجَ» sözünün mənası nədir?","options":["həyəcanlanmaq","qorxutmaq","ləğv etmək","istehza etmək, lağ etmək"],"correct":0,"id":187},
    {"type":"choice","category":"az_to_arabic","question":"«heyrətlənmək» sözünün ərəbcəsi hansıdır?","options":["اِسْتَعَانَ","أَلَّفَ","اِنْدَهَشَ","نَسِيَ"],"correct":2,"id":188},
    {"type":"choice","category":"verb_meaning","question":"«شَجَّعَ» sözünün mənası nədir?","options":["cəlb etmək","həvəsləndirmək","sınamaq","xəbər vermək"],"correct":1,"id":189},
    {"type":"choice","category":"az_to_arabic","question":"«ruh düşkünlüyünə salmaq» sözünün ərəbcəsi hansıdır?","options":["أَثَّرَ","ثَبَّطَ","سَافَرَ","اِسْتَخَارَ"],"correct":1,"id":190},
    {"type":"choice","category":"verb_meaning","question":"«سَجَّلَ» sözünün mənası nədir?","options":["tikmək, qurmaq","uzaqlaşmaq","şükr etmək","qeyd etmək"],"correct":3,"id":191},
    {"type":"choice","category":"az_to_arabic","question":"«qeyd etmək» sözünün ərəbcəsi hansıdır?","options":["سَجَلَ","كَتَبَ","اِجْتَنَبَ الشُّبُهَاتِ","تَكَبَّرَ"],"correct":0,"id":192},
    {"type":"choice","category":"verb_meaning","question":"«كَشَفَ» sözünün mənası nədir?","options":["açmaq, üzə çıxarmaq","çirkin saymaq","yerləşmək, sabit olmaq","xəbər vermək"],"correct":0,"id":193},
    {"type":"choice","category":"az_to_arabic","question":"«üzə çıxmaq» sözünün ərəbcəsi hansıdır?","options":["أَفْرَجَ","اِنْكَشَفَ","اِنْسَحَبَ","نَفَّذَ"],"correct":1,"id":194},
    {"type":"choice","category":"verb_meaning","question":"«عَادَلَ» sözünün mənası nədir?","options":["tikmək","istirahət etmək","təmizləmək","bərabərləşdirmək"],"correct":3,"id":195},
    {"type":"choice","category":"az_to_arabic","question":"«yüngülləşmək» sözünün ərəbcəsi hansıdır?","options":["قَرَّرَ","هَدَمَ","كَبَّرَ","خَفَّ"],"correct":3,"id":196},
    {"type":"choice","category":"verb_meaning","question":"«اِسْتَقْوَى» sözünün mənası nədir?","options":["əritmək","güvənmək","güclənmək","enmək, düşmək"],"correct":2,"id":197},
    {"type":"choice","category":"az_to_arabic","question":"«qatlanmaq» sözünün ərəbcəsi hansıdır?","options":["تَعَاوَنَ","تَضَاعَفَ","أَكْرَمَ الضَّيْفَ","نَشَرَ"],"correct":1,"id":198},
    {"type":"choice","category":"verb_meaning","question":"«تَحَرَّى» sözünün mənası nədir?","options":["yalançı saymaq, inkar etmək","adlandırmaq","yerləşmək, sabit olmaq","araşdırmaq"],"correct":3,"id":199},
    {"type":"choice","category":"az_to_arabic","question":"«yoxlamaq» sözünün ərəbcəsi hansıdır?","options":["حَلَّ","اِحْتَرَمَ","اِسْتَوْسَعَ","تَفَقَّدَ"],"correct":3,"id":200},
    {"type":"choice","category":"verb_meaning","question":"«خَطَّأَ» sözünün mənası nədir?","options":["səhv saymaq","tələsmək","qeyd etmək","azad olmaq"],"correct":0,"id":201},
    {"type":"choice","category":"az_to_arabic","question":"«səhv etmək» sözünün ərəbcəsi hansıdır?","options":["تَحَدَّثَ","صَارَ","حَاوَلَ","أَخْطَأَ"],"correct":3,"id":202},
    {"type":"choice","category":"verb_meaning","question":"«أَسَاءَ» sözünün mənası nədir?","options":["mane olmaq","kənara çəkilmək, təcrid olmaq","pislik etmək","haqqa sarılmaq"],"correct":2,"id":203},
    {"type":"choice","category":"az_to_arabic","question":"«təhqir etmək» sözünün ərəbcəsi hansıdır?","options":["اِصْطَلَحَ","أَلْقَى","أَهَانَ","أَحَاطَ"],"correct":2,"id":204},
    {"type":"choice","category":"verb_meaning","question":"«مَزَجَ» sözünün mənası nədir?","options":["əsasını qoymaq","girmək","qarışdırmaq","çatmaq, yetkin olmaq"],"correct":2,"id":205},
    {"type":"choice","category":"az_to_arabic","question":"«qarışdırmaq» sözünün ərəbcəsi hansıdır?","options":["خَلَطَ","طَبَخَ","تَصَدَّقَ","لَكَمَ"],"correct":0,"id":206},
    {"type":"choice","category":"verb_meaning","question":"«غَطَّى» sözünün mənası nədir?","options":["müjdələmək","çevrilmək","örtmək","dalaşmaq"],"correct":2,"id":207},
    {"type":"choice","category":"az_to_arabic","question":"«sınmaq» sözünün ərəbcəsi hansıdır?","options":["أَدْخَلَ","اِنْكَسَرَ","اِسْتَغْنَى","اِلْتَزَمَ"],"correct":1,"id":208},
    {"type":"choice","category":"verb_meaning","question":"«اِقْتَرَنَ» sözünün mənası nədir?","options":["bilmək","kirayə vermək","əvəz etmək","birləşmək"],"correct":3,"id":209},
    {"type":"choice","category":"az_to_arabic","question":"«bağlanmaq» sözünün ərəbcəsi hansıdır?","options":["اِنْقَطَعَ عَنِ المَعْصِيَةِ","اِرْتَبَطَ","عَرَفَ","رَافَقَ"],"correct":1,"id":210},
    {"type":"choice","category":"verb_meaning","question":"«طَمِعَ» sözünün mənası nədir?","options":["asan saymaq","tamah etmək","şəfaət etmək","qaçmaq"],"correct":1,"id":211},
    {"type":"choice","category":"az_to_arabic","question":"«qibtə etmək» sözünün ərəbcəsi hansıdır?","options":["غَبَطَ","أَلْغَى","قَاسَ","تَحَرَّرَ"],"correct":0,"id":212},
    {"type":"choice","category":"verb_meaning","question":"«تَلَا» sözünün mənası nədir?","options":["qınamaq","əzib məhv etmək","yardım istəmək (Allahdan)","tilavət etmək"],"correct":3,"id":213},
    {"type":"choice","category":"az_to_arabic","question":"«tərtil ilə oxumaq» sözünün ərəbcəsi hansıdır?","options":["رَتَّلَ","اِنْتَقَدَ","قَلَى","اِسْتَأْذَنَ قَبْلَ الدُّخُولِ"],"correct":0,"id":214},
    {"type":"choice","category":"verb_meaning","question":"«عَجِلَ» sözünün mənası nədir?","options":["etibarsız etmək","tərbiyə etmək","həyəcanlanmaq","tələsmək"],"correct":3,"id":215},
    {"type":"choice","category":"az_to_arabic","question":"«tələsməmək» sözünün ərəbcəsi hansıdır?","options":["اِقْتَرَحَ","اِنْحَرَفَ","طَلَّقَ","تَمَهَّلَ"],"correct":3,"id":216},
    {"type":"choice","category":"verb_meaning","question":"«قَفَلَ» sözünün mənası nədir?","options":["bağlamaq","sədəqə vermək","səyahət etmək","düşmək"],"correct":0,"id":217},
    {"type":"choice","category":"az_to_arabic","question":"«tullanmaq» sözünün ərəbcəsi hansıdır?","options":["حَرَسَ","قَفَزَ","مَضَغَ","عَمِلَ"],"correct":1,"id":218},
    {"type":"choice","category":"verb_meaning","question":"«زَلَقَ» sözünün mənası nədir?","options":["güclənmək","qalxmaq","sürüşmək","iştirak etmək"],"correct":2,"id":219},
    {"type":"choice","category":"az_to_arabic","question":"«düşmək» sözünün ərəbcəsi hansıdır?","options":["سَقَطَ","فَتَحَ","زَحَفَ","تَعَلَّمَ"],"correct":0,"id":220},
    {"type":"choice","category":"verb_meaning","question":"«لَسَعَ» sözünün mənası nədir?","options":["sancmaq","üz döndərmək, bağışlamaq","məzun olmaq","araşdırmaq"],"correct":0,"id":221},
    {"type":"choice","category":"az_to_arabic","question":"«tapdalamaq» sözünün ərəbcəsi hansıdır?","options":["دَاسَ","أَجْلَسَ","بَدَعَ","اِعْتَبَرَ"],"correct":0,"id":222},
    {"type":"choice","category":"verb_meaning","question":"«طَوَى» sözünün mənası nədir?","options":["qınamaq","müzakirə etmək, mübahisə aparmaq","dondurmaq","qatlamaq"],"correct":3,"id":223},
    {"type":"choice","category":"az_to_arabic","question":"«qatlamaq» sözünün ərəbcəsi hansıdır?","options":["طَوَّى","أَدَانَ","بَقِيَ","وَثِقَ"],"correct":0,"id":224},
    {"type":"choice","category":"verb_meaning","question":"«قَصَّرَ» sözünün mənası nədir?","options":["anlamaq","azalmaq","təcavüz etmək, həddi aşmaq","qısaltmaq"],"correct":3,"id":225},
    {"type":"choice","category":"az_to_arabic","question":"«məruz qoymaq» sözünün ərəbcəsi hansıdır?","options":["سَكَبَ","عَرَّضَ","صَلَحَ","اِعْتَنَى"],"correct":1,"id":226},
    {"type":"choice","category":"verb_meaning","question":"«اِنْحَرَفَ» sözünün mənası nədir?","options":["dağılmaq, ayrılmaq","soruşmaq","dolmaq","dönmək, sapmaq"],"correct":3,"id":227},
    {"type":"choice","category":"az_to_arabic","question":"«əyilmək» sözünün ərəbcəsi hansıdır?","options":["اِنْحَنَى","زَلَقَ","تَوَاضَعَ","رَغَّبَ"],"correct":0,"id":228},
    {"type":"choice","category":"verb_meaning","question":"«خَصَّصَ» sözünün mənası nədir?","options":["ayırmaq, təyin etmək","vəfa etmək, yerinə yetirmək","hidayət olmaq, doğru yolu tapmaq","kəsilmək, ayrılmaq, tərk etmək"],"correct":0,"id":229},
    {"type":"choice","category":"az_to_arabic","question":"«təyin etmək» sözünün ərəbcəsi hansıdır?","options":["عَيَّنَ","اِتَّجَرَ","اِكْتَفَى","تَفَرَّقَ"],"correct":0,"id":230},
    {"type":"choice","category":"verb_meaning","question":"«تَخَلَّى» sözünün mənası nədir?","options":["imtina etmək","əməkdaşlıq etmək, bir-birinə kömək etmək","getmək","yoxlamaq"],"correct":0,"id":231},
    {"type":"choice","category":"az_to_arabic","question":"«geri çəkilmək» sözünün ərəbcəsi hansıdır?","options":["مَهَّدَ","اِلْتَزَمَ بِآدَابِ الإِسْلَامِ","تَرَاجَعَ","رَبَّى"],"correct":2,"id":232},
    {"type":"choice","category":"verb_meaning","question":"«كَفَلَ» sözünün mənası nədir?","options":["başa salmaq","formalaşmaq","himayə etmək","sünnəyə bağlı qalmaq"],"correct":2,"id":233},
    {"type":"choice","category":"az_to_arabic","question":"«zəmanət vermək» sözünün ərəbcəsi hansıdır?","options":["تَأَمَّلَ","اِسْتَدَارَ","دَرَى","ضَمِنَ"],"correct":3,"id":234},
    {"type":"choice","category":"verb_meaning","question":"«أَبْطَلَ» sözünün mənası nədir?","options":["etibarsız etmək","uzaq durmaq, çəkinmək","aldatmaq, fırıldaq etmək","yaratmaq, qurmaq"],"correct":0,"id":235},
    {"type":"choice","category":"az_to_arabic","question":"«inkar etmək» sözünün ərəbcəsi hansıdır?","options":["نَفَى","حَافَظَ عَلَى الصَّلَاةِ","صَدَقَ","اِسْتَقَامَ عَلَى الحَقِّ"],"correct":0,"id":236},
    {"type":"choice","category":"verb_meaning","question":"«أَفْرَجَ» sözünün mənası nədir?","options":["itməy","kəsmək, qurban kəsmək","azad etmək","uzaq olmaq"],"correct":2,"id":237},
    {"type":"choice","category":"az_to_arabic","question":"«etiraz etmək» sözünün ərəbcəsi hansıdır?","options":["أَعَدَّ","وَظَّفَ","اِحْتَجَّ","نَظَّمَ"],"correct":2,"id":238},
    {"type":"choice","category":"verb_meaning","question":"«مَدَّ» sözünün mənası nədir?","options":["müqəddəs saymaq","tərcümə etmək","uzatmaq","əkmək"],"correct":2,"id":239},
    {"type":"choice","category":"az_to_arabic","question":"«cəlb etmək» sözünün ərəbcəsi hansıdır?","options":["اِمْتَحَنَ","جَذَبَ","رَصَدَ","اِحْتَجَّ"],"correct":1,"id":240},
    {"type":"choice","category":"verb_meaning","question":"«تَرْجَمَ» sözünün mənası nədir?","options":["borc almaq","tərcümə etmək","görüşmək, qarşılaşmaq","dişləmək"],"correct":1,"id":241},
    {"type":"choice","category":"az_to_arabic","question":"«sitat gətirmək» sözünün ərəbcəsi hansıdır?","options":["تَحَرَّكَ","فَازَ","اِسْتَدَلَّ","اِقْتَبَسَ"],"correct":3,"id":242},
    {"type":"choice","category":"verb_meaning","question":"«سَرَدَ» sözünün mənası nədir?","options":["yaratmaq, qurmaq","nəql etmək","inkar etmək","icarəyə vermək"],"correct":1,"id":243},
    {"type":"choice","category":"az_to_arabic","question":"«tərtib etmək, yazmaq» sözünün ərəbcəsi hansıdır?","options":["اِنْتَقَمَ","فَارَقَ","تَعَاوَنَ","أَلَّفَ"],"correct":3,"id":244},
    {"type":"choice","category":"verb_meaning","question":"«رَسَبَ» sözünün mənası nədir?","options":["icazə vermək","ehtiyatlı olmaq","qurumaq","imtahandan kəsilmək"],"correct":3,"id":245},
    {"type":"choice","category":"az_to_arabic","question":"«məzun olmaq» sözünün ərəbcəsi hansıdır?","options":["حَمَى","شَجَّعَ","اِلْتَزَمَ بِالطَّاعَةِ","تَخَرَّجَ"],"correct":3,"id":246},
    {"type":"choice","category":"verb_meaning","question":"«أَحْضَرَ» sözünün mənası nədir?","options":["yola salmaq","gətirmək","Allahdan bağışlanma istəmək","yedirtmək, yemək vermək"],"correct":1,"id":247},
    {"type":"choice","category":"az_to_arabic","question":"«eşitdirmək» sözünün ərəbcəsi hansıdır?","options":["زَهِدَ","حَاسَبَ","خَلَطَ","أَسْمَعَ"],"correct":3,"id":248},
    {"type":"choice","category":"verb_meaning","question":"«نَسَّى» sözünün mənası nədir?","options":["rüku etmək","unutdurmaq","bağışlanma diləmək","imtina etmək"],"correct":1,"id":249},
    {"type":"choice","category":"az_to_arabic","question":"«razı salmaq» sözünün ərəbcəsi hansıdır?","options":["اِتَّعَظَ بِمَصَارِعِ الظَّالِمِينَ","هَنَّأَ","شَرِبَ","أَرْضَى"],"correct":3,"id":250}
];
